FIRE_CHAPTERS = [
    ("fire_02_fire_fighting_history", "Fire 02 - Fire Fighting History"),
    ("fire_03_emergency_fire_services_and_fire_rescuer", "Fire 03 - Emergency Fire Services and Fire Rescuer"),
    ("fire_04_personal_protective_equipment", "Fire 04 - Personal Protective Equipment (PPE)"),
    ("fire_05_causes_of_fire", "Fire 05 - Causes of Fire"),
    ("fire_06_fire_chemistry_1", "Fire 06 - Fire Chemistry-1"),
    ("fire_07_fire_chemistry_2", "Fire 07 - Fire Chemistry-2"),
    ("fire_08_solid_and_liquid_fuel_fire_behavior", "Fire 08 - Solid and Liquid Fuel Fire Behavior"),
    ("fire_09_firefighting_tools_equipment_and_accessories", "Fire 09 - Firefighting Tools, Equipment and Accessories"),
    ("fire_10_fire_suppression", "Fire 10 - Fire Suppression"),
    ("fire_11_foam_and_foam_making_equipment", "Fire 11 - Foam and Foam Making Equipment"),
    ("fire_12_chemical_fire_1", "Fire 12 - Chemical Fire-1"),
    ("fire_13_chemical_fire_2", "Fire 13 - Chemical Fire-2"),
    ("fire_14_portable_fire_appliances", "Fire 14 - Portable Fire Appliances"),
    ("fire_15_fire_hoses", "Fire 15 - Fire Hoses"),
    ("fire_16_fire_risk_assessment", "Fire 16 - Fire Risk Assessment"),
    ("fire_17_fire_pump_and_hose_line_tactics", "Fire 17 - Fire Pump and Hose Line Tactics"),
    ("fire_18_water_supply_and_fire_hydrant", "Fire 18 - Water Supply and Fire Hydrant"),
    ("fire_19_fire_ladders", "Fire 19 - Fire Ladders"),
    ("fire_20_respiratory_protection", "Fire 20 - Respiratory Protection"),
    ("fire_21_building_protection_system", "Fire 21 - Building Protection System"),
    ("fire_22_introduction_to_fire_vehicles", "Fire 22 - Introduction to Fire Vehicles"),
    ("fire_23_specialized_fire_vehicles", "Fire 23 - Specialized Fire Vehicles"),
    ("fire_24_confined_space_entry", "Fire 24 - Confined Space Entry"),
    ("fire_25_forcible_entry", "Fire 25 - Forcible Entry"),
    ("fire_26_ventilation_at_fire", "Fire 26 - Ventilation at Fire"),
    ("fire_27_rescue_from_fire_involved_buildings", "Fire 27 - Rescue from Fire Involved Buildings"),
    ("fire_28_introduction_to_building_code_of_pakistan", "Fire 28 - Introduction to Building Code of Pakistan (BCP)"),
    ("fire_29_fire_operation_strategies_and_tactics", "Fire 29 - Fire Operation Strategies and Tactics"),
    ("fire_30_incident_command_system_and_emergency_response_level", "Fire 30 - Incident Command System and Emergency Response Level"),
    ("fire_31_repair_and_maintenance", "Fire 31 - Repair and Maintenance"),
    ("fire_32_course_review", "Fire 32 - Course Review"),
    ("fire_33_glossary", "Fire 33 - Glossary"),
    ("fire_34_building_check_list", "Fire 34 - Building Check List"),
]

RESCUE_CHAPTERS = [
    ("rescue_02_introduction_of_ropes", "Rescue 02 - Introduction of Ropes"),
    ("rescue_03_rescue_knots", "Rescue 03 - Rescue Knots"),
    ("rescue_04_personal_protective_equipment", "Rescue 04 - Personal Protective Equipment"),
    ("rescue_05_introduction_of_rope_rescue_techniques", "Rescue 05 - Introduction of Rope Rescue Techniques"),
    ("rescue_06_organising_and_starting_a_cssr_operation", "Rescue 06 - Organising and Starting a CSSR Operation"),
    ("rescue_07_well_rescue_with_tripod", "Rescue 07 - Well Rescue with Tripod"),
    ("rescue_08_well_rescue_with_ladder", "Rescue 08 - Well Rescue with Ladder"),
    ("rescue_09_height_rescue_with_basket_stretcher", "Rescue 09 - Height Rescue with Basket Stretcher"),
    ("rescue_10_construction_materials_structures_and_damage_types", "Rescue 10 - Construction Materials, Structures and Damage Types"),
    ("rescue_11_belay_techniques", "Rescue 11 - Belay Techniques"),
    ("rescue_12_ascending_and_descending", "Rescue 12 - Ascending and Descending"),
    ("rescue_13_structural_triage_and_the_insarag_marking_system", "Rescue 13 - Structural Triage and the INSARAG Marking System"),
    ("rescue_14_emergencies_and_disasters", "Rescue 14 - Emergencies and Disasters"),
    ("rescue_15_operational_safety", "Rescue 15 - Operational Safety"),
    ("rescue_16_search_and_location_techniques", "Rescue 16 - Search and Location Techniques"),
    ("rescue_17_tools_equipment_and_accessories", "Rescue 17 - Tools, Equipment and Accessories"),
    ("rescue_18_introduction_of_rescue_vehicle", "Rescue 18 - Introduction of Rescue Vehicle"),
    ("rescue_19_electrical_equipment", "Rescue 19 - Electrical Equipment"),
    ("rescue_20_internal_combustion_equipment", "Rescue 20 - Internal Combustion Equipment"),
    ("rescue_21_generators", "Rescue 21 - Generators"),
    ("rescue_22_electrical_winch", "Rescue 22 - Electrical Winch"),
    ("rescue_23_rescue_strategies_and_techniques", "Rescue 23 - Rescue Strategies and Techniques"),
    ("rescue_24_evacuation_of_casualties", "Rescue 24 - Evacuation of Casualties"),
    ("rescue_25_confined_space", "Rescue 25 - Confined Space"),
    ("rescue_26_shoring_methods", "Rescue 26 - Shoring Methods"),
    ("rescue_27_lifting_and_stabilising_loads", "Rescue 27 - Lifting and Stabilising Loads"),
    ("rescue_28_tree_trimming_safety", "Rescue 28 - Tree Trimming Safety"),
    ("rescue_29_extrication_of_victim_from_vehicle_in_rta", "Rescue 29 - Extrication of Victim from Vehicle in RTA"),
]

BUILDING_TOPICS = [
    ("building_safety", "Building Safety Regulations"),
]

QUESTION_TOPIC_LABELS = dict(FIRE_CHAPTERS + RESCUE_CHAPTERS + BUILDING_TOPICS)
